#code --list-extensions | xargs -L 1 echo code --install-extension > ext-list.txt

code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onedark
code --install-extension bierner.color-info
code --install-extension chenxsan.vscode-standardjs
code --install-extension chiragpat.tomorrow-and-tomorrow-night-operator-mono-theme
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension deerawan.vscode-faker
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-rename-tag
code --install-extension HookyQR.minify
code --install-extension joshpeng.sublime-babel-vscode
code --install-extension ms-vscode.sublime-keybindings
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension qezhu.gitlink
code --install-extension richie5um2.vscode-sort-json
code --install-extension Shan.code-settings-sync
code --install-extension shinnn.stylelint
code --install-extension sidthesloth.html5-boilerplate
code --install-extension spywhere.guides
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tyriar.sort-lines
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wwm.better-align
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
code --install-extension johnpapa.vscode-peacock
